### ISSUE TITLE
Failure due to h$withCBufferOnHeap is undefined

### ISSUE THREAD

**Issue by Crypto2099** [input-output-hk/hackage-overlay-ghcjs#4]
Experiencing test issues with Byron/Icarus addresses due to the inclusion of this patch in `cardano-addresses` due to `withCBufferOnHeap` being an undefined function as seen here: https://github.com/IntersectMBO/cardano-addresses/actions/runs/10095872827/job/27917045236#step:6:252

https://github.com/input-output-hk/hackage-overlay-ghcjs/blob/6281362356b382faf648e5161d3a58f7b0437d0f/patches/digest-0.0.1.2.patch#L41-L53

**Comment by luite** [comment]
There's also a typo: `h$withCBufferOhHeap`

**Comment by luite** [comment]
The function requires a fairly recent GHC, it was only added 5 months ago in this commit: https://gitlab.haskell.org/ghc/ghc/-/commit/aef587f65de642142c1dcba0335a301711aab951

**Comment by luite** [comment]
Perhaps we should temporarily include a copied version (with package name prefix) of that function to support earlier GHC versions in packages that use this.

**Comment by luite** [comment]
I've added them in the pull request
